# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_manager_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='manager',
            name='role',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='surveys',
            field=models.ManyToManyField(blank=True, to='core.Survey'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='volunteers',
            field=models.ManyToManyField(blank=True, to='core.Volunteer'),
        ),
    ]
