# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170404_1953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunity',
            options={'verbose_name_plural': 'opportunities'},
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='manager',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='managers',
            field=models.ManyToManyField(blank=True, to='core.Manager'),
        ),
    ]
