# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Question')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Volunteer')),
            ],
        ),
        migrations.RemoveField(
            model_name='registration',
            name='opportunity',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='question',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='volunteer',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
