# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_question_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
