# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_survey_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='answer',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
