# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20170409_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='opportunity_type',
            field=models.CharField(choices=[('action-able', 'action-able'), ('survey-able', 'survey-able')], default='survey-able', max_length=32),
        ),
    ]
