# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20170428_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='priority',
            field=models.IntegerField(default=1, help_text='This integer value represents the order                                    in which surveys appear to potential new volunteers.'),
        ),
    ]
