# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20170428_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='action_link',
            field=models.CharField(blank=True, default='', help_text='This field is only applicable to Action-able opportunities', max_length=255),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='action_text',
            field=models.CharField(blank=True, default='', help_text='This field is only applicable to Action-able opportunities', max_length=255),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='surveys',
            field=models.ManyToManyField(blank=True, help_text='This field is only applicable to Survey-able opportunities', to='core.Survey'),
        ),
    ]
