# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 21:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20170428_2117'),
        ('core', '0015_auto_20170428_1423'),
    ]

    operations = [
    ]
