# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-09 06:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_merge_20170428_2128'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='QuestionResponse',
        ),
    ]
